### ISSUE TITLE
[UI] User can see scan progress at icon in task bar.

### ISSUE THREAD

**Issue by katopz** [rabbotio/eyes#13]
Like we see in memory clean program while cleaning.
![screen shot 2017-01-04 at 23 33 57](https://cloud.githubusercontent.com/assets/97060/21650124/8f6092c8-d2d6-11e6-821d-25e984f9f611.png)

If we can't show percent maybe we can just show `scanning` with spinning ascii character animation like we saw when we do `npm i` which is `:.` `.:`

![screen shot 2017-01-04 at 23 40 41](https://cloud.githubusercontent.com/assets/97060/21650345/391f4516-d2d7-11e6-93e8-44fc0b2a4629.png)

**Comment by niponchi** [comment]
We cannot not determine how long a scanning process will take. How can we calculate the percentage from?

**Comment by katopz** [comment]
In that case we just show dot animation as mentioned above without progress bar or percentage number to let user know something running is fine enough.

**Comment by katopz** [comment]
Here's the lib 🐰  https://github.com/helloIAmPau/node-spinner

**Comment by katopz** [comment]
Please use `⣯ Spinner 28 of 30` , it will look like this while scanning.

![screen shot 2017-01-07 at 13 40 10](https://cloud.githubusercontent.com/assets/97060/21740142/39f9e9b6-d4e2-11e6-9291-b1179c7abfcf.png)

**Comment by katopz** [comment]
For other state please see https://github.com/rabbots/eyes/issues/8

**Comment by katopz** [comment]
[pending]
