### ISSUE TITLE
[Core] App can recognise dropped item type as web or Docker file.

### ISSUE THREAD

**Issue by katopz** [rabbotio/eyes#2]
- [x] Recognise dropped item type as web URL.
- [x] Recognise dropped item type as Docker file.

**Comment by niponchi** [comment]
- use regex to detect url
- use validate-dockerfile to detect a docker file

**Comment by katopz** [comment]
Issue : When drop `Dockerfile` it get upload instead of scan.
Expected : `Dockerfile` recognise and get scan instead of upload.

**Comment by niponchi** [comment]
i think it is because 'validate-dockerfile' reject the file, so it continue the Now process

**Comment by niponchi** [comment]
Fixed in Dev branch
Cause: `validate-dockerfile`, by default, fail a validation if `Dockerfile` does not contain CMD
Solution: Supply option `{quiet: true}`, to suppress CMD error detection (https://github.com/Runnable/validate-dockerfile/issues/19)
