### ISSUE TITLE
[Core] Dropped Docker file get scan with selected Docker related tools.

### ISSUE THREAD

**Issue by katopz** [rabbotio/eyes#4]
~~- [ ] https://github.com/docker/docker-bench-security~~
- [x] https://github.com/coreos/clair

**Comment by niponchi** [comment]
Validating docker file by https://github.com/Runnable/validate-dockerfile
Interacting with Clair service via: https://github.com/wemanity-belgium/hyperclair
Starting Clair service by command-line
