### ISSUE TITLE
[Core] App can save JSON,HTML results to disk.

### ISSUE THREAD

**Issue by katopz** [rabbotio/eyes#5]
- [x] Pipe CLI output to file stream as JSON.
- [x] Pipe CLI output to file stream as HTML.

**Comment by niponchi** [comment]
save to json file for now. html will be done when we done specific format

**Comment by katopz** [comment]
We'll use html results directly from tools, just save it somewhere separated by tools name and do link to it from our UI, so user can blame tools providers for wrong results and can directly file issues to them not us. We're just man in the middle don't need to touch anything.

**Comment by niponchi** [comment]
Result will be saved to '~/.rabbots/results'. Formatting of result is the same as output of the tools

**Comment by katopz** [comment]
For correction `~/.rabbot/result`
